const mongoose = require('mongoose');
const dotenv = require('dotenv');
const Car = require('./models/Car');
const User = require('./models/User');

dotenv.config();

// بيانات السيارات الوهمية
const carsData = [
  {
    brand: 'Peugeot',
    model: '208',
    year: 2022,
    mileage: '15000-50000',
    licensePlate: '123 TUN 001',
    registrationCountry: 'Tunisie',
    registrationYear: 2022,
    fuelType: 'Essence',
    transmission: 'Manuelle',
    doors: 4,
    seats: 5,
    features: ['GPS', 'Bluetooth', 'Climatisation', 'Caméra de recul'],
    carType: 'Citadine',
    userType: 'particulier',
    parkingType: 'parking privé',
    address: 'Rue de la Liberté, 15',
    city: 'Tunis',
    delegation: 'La Marsa',
    deliveryMethod: 'livraison au client',
    pricePerDay: 80,
    caution: 500,
    images: ['https://res.cloudinary.com/demo/image/upload/car1.jpg'],
    status: 'approved',
    isAvailable: true,
    isFeatured: false
  },
  {
    brand: 'Renault',
    model: 'Clio',
    year: 2021,
    mileage: '50000-100000',
    licensePlate: '123 TUN 002',
    registrationCountry: 'Tunisie',
    registrationYear: 2021,
    fuelType: 'Diesel',
    transmission: 'Manuelle',
    doors: 4,
    seats: 5,
    features: ['Bluetooth', 'Climatisation'],
    carType: 'Citadine',
    userType: 'particulier',
    parkingType: 'stationnement public',
    address: 'Avenue Habib Bourguiba, 22',
    city: 'Sfax',
    delegation: 'Sfax Ville',
    deliveryMethod: 'client rencontre le conducteur',
    pricePerDay: 70,
    caution: 400,
    images: ['https://res.cloudinary.com/demo/image/upload/car2.jpg'],
    status: 'approved',
    isAvailable: true,
    isFeatured: false
  },
  {
    brand: 'Volkswagen',
    model: 'Tiguan',
    year: 2023,
    mileage: '0-15000',
    licensePlate: '123 TUN 003',
    registrationCountry: 'Tunisie',
    registrationYear: 2023,
    fuelType: 'Essence',
    transmission: 'Automatique',
    doors: 5,
    seats: 5,
    features: ['GPS', 'Bluetooth', 'Climatisation', 'Caméra de recul', 'Radar de stationnement', 'Apple CarPlay'],
    carType: 'SUV',
    userType: 'particulier',
    parkingType: 'parking privé',
    address: 'Route de la Plage, 8',
    city: 'Sousse',
    delegation: 'Hammam Sousse',
    deliveryMethod: 'livraison au client',
    pricePerDay: 150,
    caution: 800,
    images: ['https://res.cloudinary.com/demo/image/upload/car3.jpg'],
    status: 'approved',
    isAvailable: true,
    isFeatured: true
  },
  {
    brand: 'Toyota',
    model: 'Yaris',
    year: 2020,
    mileage: '50000-100000',
    licensePlate: '123 TUN 004',
    registrationCountry: 'Tunisie',
    registrationYear: 2020,
    fuelType: 'Essence',
    transmission: 'Automatique',
    doors: 4,
    seats: 5,
    features: ['Climatisation', 'USB'],
    carType: 'Citadine',
    userType: 'particulier',
    parkingType: 'stationnement public',
    address: 'Rue de la Gare, 5',
    city: 'Nabeul',
    delegation: 'Hammamet',
    deliveryMethod: 'client rencontre le conducteur',
    pricePerDay: 90,
    caution: 500,
    images: ['https://res.cloudinary.com/demo/image/upload/car4.jpg'],
    status: 'approved',
    isAvailable: true,
    isFeatured: false
  },
  {
    brand: 'Hyundai',
    model: 'Tucson',
    year: 2022,
    mileage: '15000-50000',
    licensePlate: '123 TUN 005',
    registrationCountry: 'Tunisie',
    registrationYear: 2022,
    fuelType: 'Diesel',
    transmission: 'Automatique',
    doors: 5,
    seats: 5,
    features: ['GPS', 'Bluetooth', 'Climatisation', 'Caméra de recul', 'Radar de stationnement', 'Sièges chauffants'],
    carType: 'SUV',
    userType: 'particulier',
    parkingType: 'parking privé',
    address: 'Avenue Farhat Hached, 12',
    city: 'Monastir',
    delegation: 'Monastir',
    deliveryMethod: 'livraison au client',
    pricePerDay: 140,
    caution: 700,
    images: ['https://res.cloudinary.com/demo/image/upload/car5.jpg'],
    status: 'approved',
    isAvailable: true,
    isFeatured: false
  },
  {
    brand: 'Mercedes-Benz',
    model: 'Classe C',
    year: 2023,
    mileage: '0-15000',
    licensePlate: '123 TUN 006',
    registrationCountry: 'Tunisie',
    registrationYear: 2023,
    fuelType: 'Essence',
    transmission: 'Automatique',
    doors: 4,
    seats: 5,
    features: ['GPS', 'Bluetooth', 'Climatisation', 'Caméra de recul', 'Radar de stationnement', 'Apple CarPlay', 'Sièges chauffants', 'Toit ouvrant'],
    carType: 'Luxe',
    userType: 'professionnel',
    parkingType: 'parking privé',
    address: 'Route de la Marsa, 45',
    city: 'Tunis',
    delegation: 'La Marsa',
    deliveryMethod: 'livraison au client',
    pricePerDay: 250,
    caution: 1500,
    images: ['https://res.cloudinary.com/demo/image/upload/car6.jpg'],
    status: 'approved',
    isAvailable: true,
    isFeatured: true
  },
  {
    brand: 'Dacia',
    model: 'Duster',
    year: 2021,
    mileage: '50000-100000',
    licensePlate: '123 TUN 007',
    registrationCountry: 'Tunisie',
    registrationYear: 2021,
    fuelType: 'Diesel',
    transmission: 'Manuelle',
    doors: 5,
    seats: 5,
    features: ['Climatisation', 'USB'],
    carType: 'Utilitaire',
    userType: 'particulier',
    parkingType: 'stationnement public',
    address: 'Rue de l\'Industrie, 7',
    city: 'Bizerte',
    delegation: 'Bizerte Nord',
    deliveryMethod: 'client rencontre le conducteur',
    pricePerDay: 100,
    caution: 600,
    images: ['https://res.cloudinary.com/demo/image/upload/car7.jpg'],
    status: 'approved',
    isAvailable: true,
    isFeatured: false
  },
  {
    brand: 'Kia',
    model: 'Sportage',
    year: 2022,
    mileage: '15000-50000',
    licensePlate: '123 TUN 008',
    registrationCountry: 'Tunisie',
    registrationYear: 2022,
    fuelType: 'Essence',
    transmission: 'Automatique',
    doors: 5,
    seats: 5,
    features: ['GPS', 'Bluetooth', 'Climatisation', 'Caméra de recul'],
    carType: 'SUV',
    userType: 'particulier',
    parkingType: 'parking privé',
    address: 'Avenue de la Liberté, 18',
    city: 'Sousse',
    delegation: 'Sousse Ville',
    deliveryMethod: 'livraison au client',
    pricePerDay: 130,
    caution: 650,
    images: ['https://res.cloudinary.com/demo/image/upload/car8.jpg'],
    status: 'approved',
    isAvailable: true,
    isFeatured: false
  },
  {
    brand: 'Fiat',
    model: '500',
    year: 2020,
    mileage: '50000-100000',
    licensePlate: '123 TUN 009',
    registrationCountry: 'Tunisie',
    registrationYear: 2020,
    fuelType: 'Essence',
    transmission: 'Manuelle',
    doors: 3,
    seats: 4,
    features: ['Bluetooth'],
    carType: 'Citadine',
    userType: 'particulier',
    parkingType: 'stationnement public',
    address: 'Rue de la Kasbah, 3',
    city: 'Tunis',
    delegation: 'Tunis Médina',
    deliveryMethod: 'client rencontre le conducteur',
    pricePerDay: 60,
    caution: 400,
    images: ['https://res.cloudinary.com/demo/image/upload/car9.jpg'],
    status: 'approved',
    isAvailable: true,
    isFeatured: false
  },
  {
    brand: 'BMW',
    model: 'X5',
    year: 2023,
    mileage: '0-15000',
    licensePlate: '123 TUN 010',
    registrationCountry: 'Tunisie',
    registrationYear: 2023,
    fuelType: 'Diesel',
    transmission: 'Automatique',
    doors: 5,
    seats: 5,
    features: ['GPS', 'Bluetooth', 'Climatisation', 'Caméra de recul', 'Radar de stationnement', 'Apple CarPlay', 'Sièges chauffants', 'Toit ouvrant'],
    carType: 'Luxe',
    userType: 'professionnel',
    parkingType: 'parking privé',
    address: 'Route de Gammarth, 22',
    city: 'Tunis',
    delegation: 'La Marsa',
    deliveryMethod: 'livraison au client',
    pricePerDay: 300,
    caution: 2000,
    images: ['https://res.cloudinary.com/demo/image/upload/car10.jpg'],
    status: 'approved',
    isAvailable: true,
    isFeatured: true
  },
  {
    brand: 'Peugeot',
    model: 'Partner',
    year: 2021,
    mileage: '100000-150000',
    licensePlate: '123 TUN 011',
    registrationCountry: 'Tunisie',
    registrationYear: 2021,
    fuelType: 'Diesel',
    transmission: 'Manuelle',
    doors: 5,
    seats: 2,
    features: ['Climatisation'],
    carType: 'Utilitaire',
    userType: 'particulier',
    parkingType: 'stationnement public',
    address: 'Zone Industrielle, Lot 5',
    city: 'Sfax',
    delegation: 'Sfax Sud',
    deliveryMethod: 'client rencontre le conducteur',
    pricePerDay: 120,
    caution: 500,
    images: ['https://res.cloudinary.com/demo/image/upload/car11.jpg'],
    status: 'approved',
    isAvailable: true,
    isFeatured: false
  },
  {
    brand: 'Renault',
    model: 'Captur',
    year: 2022,
    mileage: '15000-50000',
    licensePlate: '123 TUN 012',
    registrationCountry: 'Tunisie',
    registrationYear: 2022,
    fuelType: 'Essence',
    transmission: 'Automatique',
    doors: 5,
    seats: 5,
    features: ['GPS', 'Bluetooth', 'Climatisation', 'Caméra de recul'],
    carType: 'SUV',
    userType: 'particulier',
    parkingType: 'parking privé',
    address: 'Avenue Hedi Chaker, 10',
    city: 'Sousse',
    delegation: 'Sousse Ville',
    deliveryMethod: 'livraison au client',
    pricePerDay: 110,
    caution: 550,
    images: ['https://res.cloudinary.com/demo/image/upload/car12.jpg'],
    status: 'approved',
    isAvailable: true,
    isFeatured: false
  }
];

const seedDatabase = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('✅ Connected to MongoDB');

    // الحصول على مستخدم موجود (admin أو أي مستخدم)
    const user = await User.findOne({ role: 'admin' });
    if (!user) {
      console.log('❌ No admin user found. Please create a user first.');
      process.exit(1);
    }

    // إضافة ownerId لكل سيارة
    const carsWithOwner = carsData.map(car => ({
      ...car,
      ownerId: user._id
    }));

    // حذف السيارات الموجودة (اختياري)
    // await Car.deleteMany({});
    // console.log('🗑️ Existing cars deleted');

    // إضافة السيارات الجديدة
    const result = await Car.insertMany(carsWithOwner);
    console.log(`✅ ${result.length} cars added successfully`);

    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding database:', error);
    process.exit(1);
  }
};

seedDatabase();